[simple.calt-center-ops]
ligGroup =  'center-ops'
desc = 'Vertically align some of the operators (like `*`) to the center position it is before or after a "center" operator (like `+`)'

[simple.calt-arrow]
ligGroup =  "arrow"
desc = 'Enable ligation set that forms arrows'

[simple.calt-arrow2]
ligGroup =  "arrow2"
desc = 'Enable ligation for more arrows, like `>>=`'

[simple.calt-trig]
ligGroup =  "trig"
desc = 'Enable ligation for `<|`, `|>` , `<||`, and other bar-and-angle-bracket symbols'

[simple.calt-eqeqeq]
ligGroup =  "eqeqeq"
desc = 'Enable special ligation for `===` with triple lines'

[simple.calt-eqeq]
ligGroup =  "eqeq"
desc = 'Enable ligation for `==` and `===`'

[simple.calt-ineq]
ligGroup =  "ineq"
desc = 'Enable ligation for `<=` and `>=`'

[simple.calt-exeqeq]
ligGroup =  "exeqeq"
desc = 'Enable special ligation for `!==` with triple lines'

[simple.calt-eqexeq]
ligGroup =  "eqexeq"
desc = 'Enable special ligation for `=!=` with triple lines'

[simple.calt-eqexeq-dl]
ligGroup =  "eqexeq-dl"
desc = 'Enable special ligation for `=!=` with double lines'

[simple.calt-exeq]
ligGroup =  "exeq"
desc = 'Enable ligation for `!=` and `!==`'

[simple.calt-exeq-alt-1]
ligGroup =  "exeq-alt-1"
desc = 'Enable ligation for `!=` and `!==` with a dot at below for distinction'

[simple.calt-tildeeq]
ligGroup =  "tildeeq"
desc = 'Enable ligation for `~=` as inequality'

[simple.calt-eqslasheq]
ligGroup = "eqslasheq"
desc = 'Enable special triple-line ligation for `=/=` as inequality'

[simple.calt-slasheq]
ligGroup = "slasheq"
desc = 'Enable ligation for `/=` and `=/=` as inequality'

[simple.calt-ltgt-ne]
ligGroup = "ltgt-ne"
desc = 'Enable ligation for `<>` as inequality'

[simple.calt-ltgt-diamond]
ligGroup = "ltgt-diamond"
desc = 'Enable ligation for `<>` as diamond'

[simple.calt-brst]
ligGroup = "brst"
desc = 'Center asterisk in `(*` and `*)`'

[simple.calt-plusplus]
ligGroup =  "plusplus"
desc = 'Enable ligation for `++` and further plus-chaining'

[simple.calt-kern-dotty]
ligGroup =  "kern-dotty"
desc = 'Move connecting dotty punctuations closer, like for `::`, `:::` and `...`'

[simple.calt-logic]
ligGroup =  "logic"
desc = 'Enable ligation for `/\` and `\/`'

[simple.calt-llgg]
ligGroup =  "llgg"
desc = 'Enable ligation for `<<`, `>>` and other angle-bracket chaining'

[simple.calt-llggeq]
ligGroup =  "llggeq"
desc = 'Enable ligation for `<<=`, `>>=` as shift operator'

[simple.calt-dotoper]
ligGroup =  "dotoper"
desc = 'Treat dot (`.`) as operator and perform chained centering'

[simple.calt-arrowZALE]
ligGroup =  "arrowZALE"
desc = 'Treat `<=` as arrow'

[simple.calt-arrowZAGE]
ligGroup =  "arrowZAGE"
desc = 'Treat `>=` as co-arrow'

[simple.calt-html-comment]
ligGroup =  "html-comment"
desc = 'Enable ligation for `<!--` and `<!---`'

[simple.calt-colon-greater-as-colon-arrow]
ligGroup = "colon-greater"
desc = 'Transform `:>` into `:` and a narrow arrow.'

[composite.ligset-calt]
isOptOut = true # This feature is on by default by many software
tag     = 'calt'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-llgg', 'calt-llggeq', 'calt-eqeq', 'calt-exeq', 'calt-ineq', 'calt-plusplus', 'calt-kern-dotty']
brief   = 'Default'
desc    = 'Default setting in text editors'

[composite.ligset-dlig]
tag     = 'dlig'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-arrow2', 'calt-llgg', 'calt-eqeq', 'calt-exeq', 'calt-ineq', 'calt-ltgt-diamond', 'calt-plusplus', 'calt-kern-dotty', 'calt-dotoper', 'calt-logic', 'calt-brst']
brief   = 'Discretionary'
desc    = 'Discretionary ligatures'

[composite.ligset-clike]
tag     = 'CLIK'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-llgg', 'calt-llggeq', 'calt-eqeqeq', 'calt-eqeq', 'calt-exeqeq', 'calt-exeq', 'calt-ineq', 'calt-plusplus', 'calt-kern-dotty']
desc    = 'C-Like'

[composite.ligset-javascript]
tag     = 'JSPT'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-llgg', 'calt-llggeq', 'calt-eqeqeq', 'calt-eqeq', 'calt-exeqeq', 'calt-exeq', 'calt-ineq', 'calt-plusplus', 'calt-kern-dotty']
desc    = 'JavaScript'

[composite.ligset-php]
tag     = 'PHPX'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-llgg', 'calt-llggeq', 'calt-eqeqeq', 'calt-eqeq', 'calt-exeqeq', 'calt-exeq', 'calt-ineq', 'calt-plusplus', 'calt-kern-dotty']
desc    = 'PHP'

[composite.ligset-ml]
tag     = 'MLXX'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-trig', 'calt-eqeq', 'calt-ltgt-ne', 'calt-ineq', 'calt-brst', 'calt-plusplus', 'calt-logic']
desc    = 'ML'

[composite.ligset-fsharp]
tag     = 'FSHP'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-trig', 'calt-eqeq', 'calt-ltgt-ne', 'calt-ineq', 'calt-brst', 'calt-plusplus', 'calt-logic']
desc    = 'F#'

[composite.ligset-fstar]
tag     = 'FSTA'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-trig', 'calt-eqeq', 'calt-ltgt-ne', 'calt-eqeqeq', 'calt-eqexeq', 'calt-ineq', 'calt-brst', 'calt-plusplus', 'calt-logic']
desc    = 'F*'

[composite.ligset-haskell]
tag     = 'HSKL'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-arrow2', 'calt-trig', 'calt-llgg', 'calt-eqeq', 'calt-slasheq', 'calt-ineq', 'calt-ltgt-diamond', 'calt-plusplus', 'calt-dotoper', 'calt-kern-dotty', 'calt-logic']
desc    = 'Haskell'

[composite.ligset-idris]
tag     = 'IDRS'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-arrow2', 'calt-trig', 'calt-llgg', 'calt-eqeq', 'calt-slasheq', 'calt-ineq', 'calt-ltgt-diamond', 'calt-plusplus', 'calt-dotoper', 'calt-kern-dotty', 'calt-logic']
desc    = 'Idris'

[composite.ligset-elm]
tag     = 'ELMX'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-arrow2', 'calt-trig', 'calt-llgg', 'calt-eqeq', 'calt-slasheq', 'calt-ineq', 'calt-ltgt-diamond', 'calt-plusplus', 'calt-dotoper', 'calt-kern-dotty', 'calt-logic']
desc    = 'Elm'

[composite.ligset-purescript]
tag     = 'PURS'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-arrow2', 'calt-trig', 'calt-llgg', 'calt-eqeq', 'calt-slasheq', 'calt-ineq', 'calt-ltgt-diamond', 'calt-plusplus', 'calt-dotoper', 'calt-kern-dotty', 'calt-logic']
desc    = 'PureScript'

[composite.ligset-swift]
tag     = 'SWFT'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-arrow2', 'calt-trig', 'calt-llgg', 'calt-eqeq', 'calt-exeq', 'calt-ineq', 'calt-ltgt-diamond', 'calt-plusplus']
desc    = 'Swift'

[composite.ligset-coq]
tag     = 'COQX'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-arrow2', 'calt-trig', 'calt-llgg', 'calt-eqeq', 'calt-ltgt-ne', 'calt-ineq', 'calt-plusplus', 'calt-dotoper', 'calt-logic', 'calt-brst']
desc    = 'Coq'

[composite.ligset-matlab]
tag     = 'MTLB'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-llgg', 'calt-eqeq', 'calt-tildeeq', 'calt-ineq', 'calt-plusplus', 'calt-kern-dotty']
desc    = 'Matlab'

[composite.ligset-wolfram]
tag     = 'WFLM'
buildup = ['calt-center-ops', 'calt-arrow', 'calt-trig', 'calt-ltgt-diamond', 'calt-eqeq', 'calt-exeq', 'calt-eqexeq-dl', 'calt-ineq', 'calt-brst', 'calt-plusplus', 'calt-logic', 'calt-colon-greater-as-colon-arrow']
brief   = 'Wolfram'
desc    = 'Wolfram Language (Mathematica)'
