### Editing this file for font customization is strongly discouraged.
### Use `private-build-plans.toml` to create custom fonts.
### Changing the numbers may make the builder crash / hang / produce broken shapes.

[iosevka]
naming.copyright = 'Copyright (c) 2015-2020 Belleve Invis.'
naming.licence = '''This font software is licenced under the SIL Open Font Licence, Version 1.1. This is licence is avaliable with a FAQ at: http://scripts.sil.org/OFL. This font software is distributes on an 'AS IS' basis, without warranties or conditions of any kind, either express or implied. See the SIL Open Font licence fot the specific language, premissions and limitations governing your use of this font software.'''
naming.manufacturer = 'Belleve Invis'
naming.designer = 'Belleve Invis'
naming.description = 'Spatial efficient monospace font family for programming. Built from code. http://be5invis.github.io/Iosevka'

leading = 1250     # Default line height times 1000.
descenderPad = 0   # Additional line height, added to descender.
cap = 735          # Cap height (as well as ascender).
xheight = 530      # X-height.
#descender = -205  # Depth of descender. Currently unused.
winMetricAscenderPad  = 0 # Padding of Win ascnder metrics to avoid clipping. See #343
winMetricDescenderPad = 0 # Padding of Win descender metrics to avoid clipping. See #343

SymbolMid = 340    # Center of parens, maths, geometrics...
parenSize = 966    # Size of parens, brackets, braces, slashes, etc.
operSize = 0.80    # Size of mathematical operators (cups, etc.)
tackSize = 0.80    # Size of logical operators (tacks, etc.)
bgopSize = 1.10    # Size of "taller" mathematical operators
plusSize = 0.52    # Size of plus and arith symbols
pictSize = 1.10    # Size of pictograms
arrowHeight = 1.50 # Height of arrows

contrast = 1.11111 # Stroke width contrast.

slopeAngle = 0     # slope angle, in degrees.

accent = 155       # Height of accent marks.
accentx = 200      # Width of accent marks.
overshoot = -8     # Vertical overshoot for arcs.
overshootx = -8    # Horizontal overshoot for arcs.
oxhook = -2        # Horizontal overshoot for hook tips.
fovershoot = -40   # Overshoot of the top end of italic `f`.

shoulderfineMin = 0.8

isItalic = false   # Use italic shapes?
isOblique = false  # Use oblique shapes?

spacing = 1        # Spacing indicator

# Powerline-specific parameters
powerlineScaleY = 1 # Vertical scale
powerlineScaleX = 1 # Horizontal scale
powerlineShiftY = 0 # Vertical shift
powerlineShiftX = 0 # Horizontal shift

# Whether to generate CV-SS features
enableCvSs = true

# Whether to generate ligation
enableLigation = true

# Excluded code points
excludedCharRanges = []

[verbose]
verbose = true

###### Slab variant
[slab]
slab = true

###### Spacings
# Terminal variant
[sp-term]
spacing = 0

# "FontFonfig Monospace"
[sp-force-monospace]
spacing = 0
forceMonospace = true

# Fixed variant
[sp-fixed]
spacing = 0
enableLigation = false
forceMonospace = true

###### Disabling Ligation
[no-ligation]
enableLigation = false
[nolig] # For compatibility
enableLigation = false

###### Disabling CV/SS
[no-cv-ss]
enableCvSs = false

###### Slopes
[s-italic]
isItalic = true
slopeAngle = 10
jhook = 120

[s-oblique]
isOblique = true
slopeAngle = 10
jhook = 120

###### Diversity
[diversity-0]
diversityM = 1
diversityF = 1
diversityI = 1
diversityII = 1

[diversity-1]
diversityM = 1.25
diversityF = 1.00
diversityI = 0.75
diversityII = 0.75

[diversity-2]
diversityM = 1.25
diversityF = 0.75
diversityI = 0.75
diversityII = 0.5

###### Old-style figures
[default-to-old-style-figures]
defaultToOldStyleFigures = true

[default-to-old-style-digits]
defaultToOldStyleFigures = true

[default-to-lining-figures]
defaultToOldStyleFigures = false

[default-to-lining-digits]
defaultToOldStyleFigures = false

###################################################################################################
### Metric-override hives
### These hives are now discouraged in favor of 'metric-override' in build plans but they are
### still supported in version 3.x.

###### Leading
[leading-750]
leading = 750
[leading-1000]
leading = 1000
[leading-1250]
leading = 1250
[leading-1500]
leading = 1500
[leading-1750]
leading = 1750
[leading-2000]
leading = 2000

###### Win metric pad
[win-metric-pad-0]
winMetricAscenderPad = 0
winMetricDescenderPad = 0
[win-metric-pad-50]
winMetricAscenderPad = 50
winMetricDescenderPad = 50
[win-metric-pad-100]
winMetricAscenderPad = 100
winMetricDescenderPad = 100
[win-metric-pad-150]
winMetricAscenderPad = 150
winMetricDescenderPad = 150
[win-metric-pad-200]
winMetricAscenderPad = 200
winMetricDescenderPad = 200
[win-metric-pad-250]
winMetricAscenderPad = 250
winMetricDescenderPad = 250
[win-metric-pad-300]
winMetricAscenderPad = 300
winMetricDescenderPad = 300

###### Powerline
[powerline-scale-y-750]
powerlineScaleY = 0.75
[powerline-scale-y-875]
powerlineScaleY = 0.875
[powerline-scale-y-1000]
powerlineScaleY = 1
[powerline-scale-y-1125]
powerlineScaleY = 1.125
[powerline-scale-y-1250]
powerlineScaleY = 1.25
[powerline-scale-y-1375]
powerlineScaleY = 1.375
[powerline-scale-y-1500]
powerlineScaleY = 1.5
[powerline-scale-x-750]
powerlineScaleX = 0.75
[powerline-scale-x-875]
powerlineScaleX = 0.875
[powerline-scale-x-1000]
powerlineScaleX = 1
[powerline-scale-x-1125]
powerlineScaleX = 1.125
[powerline-scale-x-1250]
powerlineScaleX = 1.25
[powerline-scale-x-1375]
powerlineScaleX = 1.375
[powerline-scale-x-1500]
powerlineScaleX = 1.5
[powerline-shift-y-n500]
powerlineShiftY = -500
[powerline-shift-y-n450]
powerlineShiftY = -450
[powerline-shift-y-n400]
powerlineShiftY = -400
[powerline-shift-y-n350]
powerlineShiftY = -350
[powerline-shift-y-n300]
powerlineShiftY = -300
[powerline-shift-y-n250]
powerlineShiftY = -250
[powerline-shift-y-n200]
powerlineShiftY = -200
[powerline-shift-y-n150]
powerlineShiftY = -150
[powerline-shift-y-n100]
powerlineShiftY = -100
[powerline-shift-y-n50]
powerlineShiftY = -50
[powerline-shift-y-0]
powerlineShiftY = 0
[powerline-shift-y-p50]
powerlineShiftY = 50
[powerline-shift-y-p100]
powerlineShiftY = 100
[powerline-shift-y-p150]
powerlineShiftY = 150
[powerline-shift-y-p200]
powerlineShiftY = 200
[powerline-shift-y-p250]
powerlineShiftY = 250
[powerline-shift-y-p300]
powerlineShiftY = 300
[powerline-shift-y-p350]
powerlineShiftY = 350
[powerline-shift-y-p400]
powerlineShiftY = 400
[powerline-shift-y-p450]
powerlineShiftY = 450
[powerline-shift-y-p500]
powerlineShiftY = 500
[powerline-shift-x-n500]
powerlineShiftX = -500
[powerline-shift-x-n450]
powerlineShiftX = -450
[powerline-shift-x-n400]
powerlineShiftX = -400
[powerline-shift-x-n350]
powerlineShiftX = -350
[powerline-shift-x-n300]
powerlineShiftX = -300
[powerline-shift-x-n250]
powerlineShiftX = -250
[powerline-shift-x-n200]
powerlineShiftX = -200
[powerline-shift-x-n150]
powerlineShiftX = -150
[powerline-shift-x-n100]
powerlineShiftX = -100
[powerline-shift-x-n50]
powerlineShiftX = -50
[powerline-shift-x-0]
powerlineShiftX = 0
[powerline-shift-x-p50]
powerlineShiftX = 50
[powerline-shift-x-p100]
powerlineShiftX = 100
[powerline-shift-x-p150]
powerlineShiftX = 150
[powerline-shift-x-p200]
powerlineShiftX = 200
[powerline-shift-x-p250]
powerlineShiftX = 250
[powerline-shift-x-p300]
powerlineShiftX = 300
[powerline-shift-x-p350]
powerlineShiftX = 350
[powerline-shift-x-p400]
powerlineShiftX = 400
[powerline-shift-x-p450]
powerlineShiftX = 450
[powerline-shift-x-p500]
powerlineShiftX = 500

# Compatibility PUA ligature sample
# [[iosevka.compLig]]
# unicode = 57600 # 0xE100
# featureTag = 'XV00'
# sequence = '<*>'

# Exclude code points
[exclude-check-and-cross-symbol.appends]
excludedCharRanges = [[10003, 10008]]
