[shapeWeight.blend.400]
stroke = 72       # Primary stroke width
sb = 60           # Primary sidebearings
essx = 1.12       # Proportion of widen of center of "S"
dotsize = 125     # Size of dots
periodsize = 140  # Size of period

jut = 85          # Length of slab serif
refJut = 85       # Reference JUT, used in `m`
vjut = 145        # Length of vertical slab serif
longjut = 175     # Length of long serifs, like that in `i`.

smooth = 195              # Vertical arc size in capital letters.
smallsmooth = 200         # Vertical arc size in lowercase letters.

rbalance = 60
rbalance2 = 15
tbalance = 50
tbalance2 = 30
jbalance = 63
fbalance = 6
onebalance = 30

hook  = 155        # Hook depth in most letters.
ahook = 130
shook = 110
jhook = 135
fhook = 120
hookx = 170
rhook = 110

cthin = 0.75
cthinb = 0.5
vtipfine = 0.8
vtipfineSlab = 0.9

[shapeWeight.blend.100]
jut = 70
vjut = 145
smooth = 195
rhook = 110
rbalance = 60
rbalance2 = 15
cthin = 0.9
cthinb = 0.9
vtipfine = 1
vtipfineSlab = 1
stroke = 18
sb = 72
dotsize = 53
periodsize = 55

[shapeWeight.blend.200]
jut = 75
vjut = 145
smooth = 195
rhook = 110
rbalance = 60
rbalance2 = 15
cthin = 0.75
cthinb = 0.75
vtipfine = 1
vtipfineSlab = 1
stroke = 36
sb = 68
dotsize = 70
periodsize = 77

[shapeWeight.blend.300]
jut = 80
vjut = 145
smooth = 195
rhook = 110
rbalance = 60
rbalance2 = 15
cthin = 0.75
cthinb = 0.5
vtipfine = 0.9
vtipfineSlab = 0.9
stroke = 56
sb = 64
dotsize = 100
periodsize = 115

[shapeWeight.blend.500]
essx = 1.12
jut = 85
vjut = 157
smooth = 200
rhook = 110
rbalance = 60
rbalance2 = 15
stroke = 84
sb = 57
dotsize = 135
periodsize = 160

[shapeWeight.blend.600]
essx = 1.07
jut = 85
vjut = 170
smooth = 203
rhook = 110
rbalance = 55
rbalance2 = 20
stroke = 97
sb = 54
dotsize = 145
periodsize = 168

[shapeWeight.blend.700]
essx = 1.06
jut = 89
vjut = 179
smooth = 206
rhook = 95
rbalance = 52
rbalance2 = 23
stroke = 106
sb = 50
dotsize = 157
periodsize = 180

[shapeWeight.blend.800]
essx = 1.05
jut = 96
vjut = 189
smooth = 210
rhook = 97
rbalance = 50
rbalance2 = 25
stroke = 116
sb = 45
dotsize = 167
periodsize = 188

[shapeWeight.blend.900]
essx = 1.03
jut = 100
vjut = 199
smooth = 215
rhook = 105
rbalance = 50
rbalance2 = 25
stroke = 126
sb = 42
dotsize = 180
periodsize = 200
