# Build options
[buildOptions]
optimizeWithTtx = false

# Building plans
# Sans
[buildPlans.iosevka]
family = "Iosevka"
snapshotFamily = 'iosevka'

[buildPlans.iosevka-fixed]
family = "Iosevka Fixed"
design = ["sp-fixed"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on'

[buildPlans.iosevka-term]
family = "Iosevka Term"
design = ["sp-term"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on'

# Slab
[buildPlans.iosevka-slab]
family = "Iosevka Slab"
design = ["slab"]
snapshotFamily = 'iosevka-slab'

[buildPlans.iosevka-fixed-slab]
family = "Iosevka Fixed Slab"
design = ["sp-fixed", "slab"]
snapshotFamily = 'iosevka-slab'
snapshotFeature = '"NWID" on'

[buildPlans.iosevka-term-slab]
family = "Iosevka Term Slab"
design = ["sp-term", "slab"]
snapshotFamily = 'iosevka-slab'
snapshotFeature = '"NWID" on'

# Curly
[buildPlans.iosevka-curly]
family  = "Iosevka Curly"
design  = ["ss20"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss20" on'

[buildPlans.iosevka-fixed-curly]
family  = "Iosevka Fixed Curly"
design  = ["sp-fixed", "ss20"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss20" on'

[buildPlans.iosevka-term-curly]
family  = "Iosevka Term Curly"
design  = ["sp-term", "ss20"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss20" on'

# Curly Slab
[buildPlans.iosevka-curly-slab]
family  = "Iosevka Curly Slab"
design  = ["slab", "ss20"]
snapshotFamily = 'iosevka-slab'
snapshotFeature = '"ss20" on'


[buildPlans.iosevka-fixed-curly-slab]
family  = "Iosevka Fixed Curly Slab"
design  = ["sp-fixed", "slab", "ss20"]
snapshotFamily = 'iosevka-slab'
snapshotFeature = '"NWID" on, "ss20" on'


[buildPlans.iosevka-term-curly-slab]
family  = "Iosevka Term Curly Slab"
design  = ["sp-term", "slab", "ss20"]
snapshotFamily = 'iosevka-slab'
snapshotFeature = '"NWID" on, "ss20" on'


###################################################################################################
# SSxx
[buildPlans.iosevka-ss01]
family = "Iosevka SS01"
design = ["ss01"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss01" on'

[buildPlans.iosevka-fixed-ss01]
family = "Iosevka Fixed SS01"
design = ["sp-fixed", "ss01"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss01" on'

[buildPlans.iosevka-term-ss01]
family = "Iosevka Term SS01"
design = ["sp-term", "ss01"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss01" on'

[buildPlans.iosevka-ss02]
family = "Iosevka SS02"
design = ["ss02"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss02" on'

[buildPlans.iosevka-fixed-ss02]
family = "Iosevka Fixed SS02"
design = ["sp-fixed", "ss02"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss02" on'

[buildPlans.iosevka-term-ss02]
family = "Iosevka Term SS02"
design = ["sp-term", "ss02"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss02" on'


[buildPlans.iosevka-ss03]
family = "Iosevka SS03"
design = ["ss03"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss03" on'

[buildPlans.iosevka-fixed-ss03]
family = "Iosevka Fixed SS03"
design = ["sp-fixed", "ss03"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss03" on'

[buildPlans.iosevka-term-ss03]
family = "Iosevka Term SS03"
design = ["sp-term", "ss03"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss03" on'


[buildPlans.iosevka-ss04]
family = "Iosevka SS04"
design = ["ss04"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss04" on'

[buildPlans.iosevka-fixed-ss04]
family = "Iosevka Fixed SS04"
design = ["sp-fixed", "ss04"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss04" on'

[buildPlans.iosevka-term-ss04]
family = "Iosevka Term SS04"
design = ["sp-term", "ss04"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss04" on'


[buildPlans.iosevka-ss05]
family = "Iosevka SS05"
design = ["ss05"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss05" on'

[buildPlans.iosevka-fixed-ss05]
family = "Iosevka Fixed SS05"
design = ["sp-fixed", "ss05"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss05" on'

[buildPlans.iosevka-term-ss05]
family = "Iosevka Term SS05"
design = ["sp-term", "ss05"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss05" on'


[buildPlans.iosevka-ss06]
family = "Iosevka SS06"
design = ["ss06"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss06" on'

[buildPlans.iosevka-fixed-ss06]
family = "Iosevka Fixed SS06"
design = ["sp-fixed", "ss06"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss06" on'

[buildPlans.iosevka-term-ss06]
family = "Iosevka Term SS06"
design = ["sp-term", "ss06"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss06" on'


[buildPlans.iosevka-ss07]
family = "Iosevka SS07"
design = ["ss07"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss07" on'

[buildPlans.iosevka-fixed-ss07]
family = "Iosevka Fixed SS07"
design = ["sp-fixed", "ss07"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss07" on'

[buildPlans.iosevka-term-ss07]
family = "Iosevka Term SS07"
design = ["sp-term", "ss07"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss07" on'


# The SS08 has curly bars, so apply ss20 first
[buildPlans.iosevka-ss08]
family = "Iosevka SS08"
design = ["ss08"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss08" on'

[buildPlans.iosevka-fixed-ss08]
family = "Iosevka Fixed SS08"
design = ["sp-fixed", "ss08"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss08" on'

[buildPlans.iosevka-term-ss08]
family = "Iosevka Term SS08"
design = ["sp-term", "ss08"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss08" on'


[buildPlans.iosevka-ss09]
family = "Iosevka SS09"
design = ["ss09"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss09" on'

[buildPlans.iosevka-fixed-ss09]
family = "Iosevka Fixed SS09"
design = ["sp-fixed", "ss09"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss09" on'

[buildPlans.iosevka-term-ss09]
family = "Iosevka Term SS09"
design = ["sp-term", "ss09"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss09" on'


[buildPlans.iosevka-ss10]
family = "Iosevka SS10"
design = ["ss10"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss10" on'

[buildPlans.iosevka-fixed-ss10]
family = "Iosevka Fixed SS10"
design = ["sp-fixed", "ss10"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss10" on'

[buildPlans.iosevka-term-ss10]
family = "Iosevka Term SS10"
design = ["sp-term", "ss10"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss10" on'


[buildPlans.iosevka-ss11]
family = "Iosevka SS11"
design = ["ss11"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss11" on'

[buildPlans.iosevka-fixed-ss11]
family = "Iosevka Fixed SS11"
design = ["sp-fixed", "ss11"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss11" on'

[buildPlans.iosevka-term-ss11]
family = "Iosevka Term SS11"
design = ["sp-term", "ss11"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss11" on'


[buildPlans.iosevka-ss12]
family = "Iosevka SS12"
design = ["ss12"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss12" on'

[buildPlans.iosevka-fixed-ss12]
family = "Iosevka Fixed SS12"
design = ["sp-fixed", "ss12"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss12" on'

[buildPlans.iosevka-term-ss12]
family = "Iosevka Term SS12"
design = ["sp-term", "ss12"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss12" on'


[buildPlans.iosevka-ss13]
family = "Iosevka SS13"
design = ["ss13"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss13" on'

[buildPlans.iosevka-fixed-ss13]
family = "Iosevka Fixed SS13"
design = ["sp-fixed", "ss13"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss13" on'

[buildPlans.iosevka-term-ss13]
family = "Iosevka Term SS13"
design = ["sp-term", "ss13"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss13" on'


[buildPlans.iosevka-ss14]
family = "Iosevka SS14"
design = ["ss14"]
snapshotFamily = 'iosevka'
snapshotFeature = '"ss14" on'

[buildPlans.iosevka-fixed-ss14]
family = "Iosevka Fixed SS14"
design = ["sp-fixed", "ss14"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss14" on'

[buildPlans.iosevka-term-ss14]
family = "Iosevka Term SS14"
design = ["sp-term", "ss14"]
snapshotFamily = 'iosevka'
snapshotFeature = '"NWID" on, "ss14" on'

###################################################################################################
# Proportional families
[buildPlans.iosevka-aile]
family  = "Iosevka Aile"
design  = ["type", "v-at-fourfold", "v-j-narrow", 'v-capital-i-straight', 'v-capital-j-straight', 'v-g-singlestorey', 'v-r-narrow', "no-cv-ss", "no-ligation", 'v-a-doublestorey', 'v-d-toothed', 'v-u-with-bar']
upright = ["v-i-line", "v-l-line", 'v-f-narrow', 'v-t-narrow']
italic  = ["v-i-line", "v-l-line", 'v-f-narrow', 'v-t-narrow']
oblique = ["v-i-line", "v-l-line", 'v-f-narrow', 'v-t-narrow']
snapshotFamily = 'iosevka-aile'
quasiProportionalDiversity = 2

[buildPlans.iosevka-aile.widths.normal]
shape = 576
menu  = 5
css   = "normal"




[buildPlans.iosevka-etoile]
family  = "Iosevka Etoile"
design  = ["type", "slab", "v-at-fourfold", 'v-j-serifed', 'no-cv-ss', "no-ligation"]
upright = ['v-i-serifed', 'v-l-serifed']
italic  = ['v-i-italic', 'v-l-italic']
oblique = ['v-i-serifed', 'v-l-serifed']
snapshotFamily = 'iosevka-etoile'
quasiProportionalDiversity = 1

[buildPlans.iosevka-etoile.widths.normal]
shape = 576
menu  = 5
css   = "normal"




[buildPlans.iosevka-sparkle]
family  = "Iosevka Sparkle"
design  = ["type", "v-at-fourfold", "v-j-narrow-serifed", "no-cv-ss", "no-ligation"]
upright = ['v-i-serifed', 'v-l-serifed', "v-f-serifed", "v-r-serifed"]
italic  = ['v-i-italic', 'v-l-italic', "v-f-tailed", 'v-r-top-serifed']
oblique = ['v-i-serifed', 'v-l-serifed', "v-f-serifed", "v-r-serifed"]
snapshotFamily = 'iosevka-sparkle'
quasiProportionalDiversity = 1

[buildPlans.iosevka-sparkle.widths.normal]
shape = 576
menu  = 5
css   = "normal"

###################################################################################################
# Collect plans
[collectPlans.iosevka]
from = [
	"iosevka",
	"iosevka-fixed",
	"iosevka-term"
]

[collectPlans.iosevka-slab]
from = [
	"iosevka-slab",
	"iosevka-fixed-slab",
	"iosevka-term-slab"
]

[collectPlans.iosevka-curly]
from = [
	"iosevka-curly",
	"iosevka-fixed-curly",
	"iosevka-term-curly"
]

[collectPlans.iosevka-curly-slab]
from = [
	"iosevka-curly-slab",
	"iosevka-fixed-curly-slab",
	"iosevka-term-curly-slab"
]

[collectPlans.iosevka-ss01]
from = [
	"iosevka-ss01",
	"iosevka-fixed-ss01",
	"iosevka-term-ss01"
]

[collectPlans.iosevka-ss02]
from = [
	"iosevka-ss02",
	"iosevka-fixed-ss02",
	"iosevka-term-ss02"
]

[collectPlans.iosevka-ss03]
from = [
	"iosevka-ss03",
	"iosevka-fixed-ss03",
	"iosevka-term-ss03"
]

[collectPlans.iosevka-ss04]
from = [
	"iosevka-ss04",
	"iosevka-fixed-ss04",
	"iosevka-term-ss04"
]

[collectPlans.iosevka-ss05]
from = [
	"iosevka-ss05",
	"iosevka-fixed-ss05",
	"iosevka-term-ss05"
]

[collectPlans.iosevka-ss06]
from = [
	"iosevka-ss06",
	"iosevka-fixed-ss06",
	"iosevka-term-ss06"
]

[collectPlans.iosevka-ss07]
from = [
	"iosevka-ss07",
	"iosevka-fixed-ss07",
	"iosevka-term-ss07"
]

[collectPlans.iosevka-ss08]
from = [
	"iosevka-ss08",
	"iosevka-fixed-ss08",
	"iosevka-term-ss08"
]

[collectPlans.iosevka-ss09]
from = [
	"iosevka-ss09",
	"iosevka-fixed-ss09",
	"iosevka-term-ss09"
]

[collectPlans.iosevka-ss10]
from = [
	"iosevka-ss10",
	"iosevka-fixed-ss10",
	"iosevka-term-ss10"
]

[collectPlans.iosevka-ss11]
from = [
	"iosevka-ss11",
	"iosevka-fixed-ss11",
	"iosevka-term-ss11"
]

[collectPlans.iosevka-ss12]
from = [
	"iosevka-ss12",
	"iosevka-fixed-ss12",
	"iosevka-term-ss12"
]

[collectPlans.iosevka-ss13]
from = [
	"iosevka-ss13",
	"iosevka-fixed-ss13",
	"iosevka-term-ss13"
]

[collectPlans.iosevka-ss14]
from = [
	"iosevka-ss14",
	"iosevka-fixed-ss14",
	"iosevka-term-ss14"
]

[collectPlans.iosevka-aile]
from = ["iosevka-aile"]

[collectPlans.iosevka-etoile]
from = ["iosevka-etoile"]

[collectPlans.iosevka-sparkle]
from = ["iosevka-sparkle"]

[collectConfig]
distinguishWeights = true
distinguishWidths = false
distinguishSlope = false

###################################################################################################
# Weight mappings (style => shape weight, menu weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   Menu weight  : affects the font menu name
#   CSS weight   : affects the webfont CSS "font-weight" property
# IMPORTANT : Currently "menu" property only support 100, 200, 300, 400, 500, 600, 700, 800, 900.
#              and "shape" properly only supports number between 100 and 900 (inclusive).

[weights.thin]
shape = 100
menu  = 100
css   = 100

[weights.extralight]
shape = 200
menu  = 200
css   = 200

[weights.light]
shape = 300
menu  = 300
css   = 300

[weights.regular]
shape = 400
menu  = 400
css   = 400

[weights.medium]
shape = 500
menu  = 500
css   = 500

[weights.semibold]
shape = 600
menu  = 600
css   = 600

[weights.bold]
shape = 700
menu  = 700
css   = 700

[weights.extrabold]
shape = 800
menu  = 800
css   = 800

[weights.heavy]
shape = 900
menu  = 900
css   = 900

# slope mappings (style => CSS)
# NOTE: This mapping does NOT affect the font's metadata, only affects
#       the webfont CSS. Change `params/parameters.toml` instead.
[slopes]
upright = "normal"
oblique = "oblique"
italic = "italic"

# Width mappings (style => shape width, menu width, CSS stretch)
#   Shape width   : affects the shape of the glyphs
#   Menu width    : affects the font menu name
#   CSS stretch   : affects the webfont CSS "font-stretch" property
#
# IMPORTANT : Currently "shape" property only support 3 ... 9
#              and "menu" only support 1 ... 9

[widths.normal]
shape = 500
menu  = 5
css   = "normal"

[widths.extended]
shape = 576
menu  = 7
css   = "expanded"

