[buildPlans.Mun]
family = "mun"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Mun.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "two-arcs"
four = "semi-open-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "straight-serifless"
zero = "tall-slashed"
capital-g = "toothless-corner-serifless-capped"
capital-j = "serifless"
capital-l = "serifless"
capital-q = "crossing"
capital-w = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-tailed"
c = "serifless"
f = "tailed"
g = "single-storey-serifless"
i = "serifless"
j = "serifed"
l = "flat-tailed"
q = "earless-corner-tailed-serifless"
u = "tailed-serifless"
x = "straight-serifless"
y = "cursive-serifless"
capital-eszet = "rounded-serifless"
long-s = "flat-hook-tailed"
eszet = "traditional-serifless"
caret = "high"
brace = "curly"
at = "fourfold"
percent = "rings-continuous-slash"
question = "corner"
